server:
  port: 8090
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/yogurt_dev?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: yogurt_api_dev
    password: dev123
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 600000

  flyway:
    enabled: true
    baseline-on-migrate: false
    locations: classpath:db/migration
    user: yogurt_flyway
    password: flyway123